= Concurrent Programming - Second Work Assignment

== Introduction

This document contains the requirements for the second work assignment of the Concurrent Programming (_Programação Concorrente_) course.
The solution to this work assignment must be delivered until the end of 2025-05-03 (end of week 11), via the creation and push of the `0.2.0` Git tag.
For each requirement:

* Include technical documentation with the solution design, e.g. as a KDoc for the complete class (e.g. link:https://github.com/Kotlin/kotlinx.coroutines/blob/master/kotlinx-coroutines-core/common/src/CoroutineScope.kt#L11-L74[example]).
* Include automated tests, including both basic functional tests and _stress tests_.

This work assignment should be done in groups of 3 students.

=== Requirement 1 - `AutoResetLatch` class

Design and implement the `AutoResetLatch` synchronizer with the following interface:

.The `AutoResetLatch` class
[#AutoResetLatch,kotlin]   
----
class AutoResetLatch {

    fun set(): Long

    @Throws(InterruptedException::class)
    fun await(timeout: Duration): Boolean
}
----

The `AutoResetLatch` allows threads to _await_ until another thread calls `set`. This await can end unsuccessfully if:
* The `timeout` duration elapses without another thread calling `set`, in which case the `await` call returns `false`.
* The thread blocked on `await` is interrupted, in which case the `await` call ends by throwing `InterruptedException`.

A call to `set` only unblocks the threads that are waiting at the specific moment in time, returning the number of unblocked threads.
The synchronizer is called _auto reset_ because a call to `set` doesn't have any consequence on future calls to `await`.
If a call to `set` returns _N_, then _N_ calls to `await` also return `true`.
That is, if a thread ends `await` non-successfully, then it should not count toward the number returned by `set`.

=== Requirement 2 - `ThreadPool` class

Implement the _thread pool executor synchronizer_, in which each submitted _continuation_ is executed on one of the worker threads that the synchronizer creates and manages for this purpose. 
The public interface of this synchronizer is the following one:

.The `ThreadPool` class
[#ThreadPool, kotlin]
----
class ThreadPool(
    private val minThreadPoolSize: Int,
    private val maxThreadPoolSize: Int,
    private val keepAliveTime: Duration,
) {
    init { 
            require (
                minThreadPoolSize > 0 && 
                maxThreadPoolSize > 0 && 
                minThreadPoolSize <= maxThreadPoolSize
            )
    }

    @Throws(RejectedExecutionException::class)
    fun execute(continuation: Continuation<Unit>): Unit { … }

    fun shutdown(): Unit { … }

    @Throws(InterruptedException::class)
    fun awaitTermination(timeout: Duration): Boolean { … }
}
----

The minimum number of worker threads, the maximum number of worker threads, and the maximum time that a worker thread can remain idle before terminating are passed as `ThreadPool` constructor arguments.
The management of the worker threads by the synchronizer must follow these criteria:

* If the total number of worker threads is less than the specified maximum limit and no worker thread is available, a new worker thread is created whenever a continuation is submitted for execution.

* Worker threads should terminate after the amount of time specified in `keepAliveTime` has passed without them being assigned a continuation to execute, unless the total number of threads would go below `minThreadPoolSize`.

* The number of worker threads in the pool at any given moment depends on its activity and can vary between `minThreadPoolSize` and `maxThreadPoolSize`.

A call to the `execute`` method submits a continuation to be executed by the thread pool executor.
This method returns immediately, without waiting for the continuation to be executed or even submitted to a worker thread.

Calling the `shutdown` method puts the executor in _shutdown_ mode and returns immediately.
In this mode, all subsequent calls to the `execute` method must throw a `RejectedExecutionException`. 
However, all continuations submitted before the call to `shutdown` must be processed normally.

The `awaitTermination` method allows any calling thread to synchronize with the completion of the executor's shutdown process. That is, it waits until all accepted continuations are executed and all active worker threads have terminated. It may finish:

* normally, returning true if the shutdown of the executor completes;

* normally, returning false if the timeout specified as an argument expires before shutdown completes;

* exceptionally, by throwing `InterruptedException` if the calling thread is interrupted while waiting.

After a call to `shutdown`, the number of threads can go below `minThreadPoolSize`.

=== Requirement 3 - `ThreadPool.invoke` extension function

Create the `suspend fun <R> ThreadPool.invoke(f: () -> R): R` extension function.
This function promotes the execution of the `f` function in the context `ThreadPool` instance, waiting for that execution to complete and then returning its result.
A call to `invoke` must not block the thread where that call was made.

=== Requirement 4 - `PeriodicMessage`

Consider the following definitions:

[#PeriodicMessage, kotlin] 
----
data class PeriodicMessage(
    val delayBetweenStrings: Duration,
    val nOfRepetitions: Int,
    val strings: List<String>,
) {
    init {
        require(nOfRepetitions > 0)
    }
}

fun show(showLine: (line: String) -> Unit, vararg periodicMessages: PeriodicMessage) {...}
----

Implement the `show` function that concurrently shows all periodic messages provided as arguments, using the provided
`showLine` function.
The `show` function returns when all periodic messages are completely shown.
The implementation should take advantage of suspend functions; specifically, each periodic message must be shown using the following suspend function, where `waitUntil` is an internal auxiliary function to be implemented.

[#showPeriodicMessage, kotlin] 
----
suspend fun showPeriodicMessage(msg: PeriodicMessage) {
    val startInstant = Instant.now()
    var nextInstant = startInstant.plus(msg.delayBetweenStrings)
    repeat(msg.nOfRepetitions) {
        msg.strings.forEach { string ->
            showLine(string)
            waitUntil(nextInstant)
            nextInstant = nextInstant.plus(msg.delayBetweenStrings)
        }
    }
}
----

The implementation of this requirement must not create any threads, directly or indirectly (e.g. via an executor). Namely, all `showLine` calls should occur in the thread that called `show`.
Do not use any functionality from the `kotlinx.coroutines` package.
